# Generated by Django 3.1.5 on 2021-02-08 22:57

import apps.portfolio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_screenshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to=apps.portfolio.models.Screenshot.generate_upload_directory),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='portfolio.project'),
        ),
    ]
