# Generated by Django 3.1.5 on 2021-02-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210208_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Developer', max_length=100),
            preserve_default=False,
        ),
    ]
