# Generated by Django 3.1.5 on 2021-02-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_technologyperproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologyperproject',
            options={'verbose_name_plural': 'Technologies Per Project'},
        ),
        migrations.AddConstraint(
            model_name='technologyperproject',
            constraint=models.UniqueConstraint(fields=('project', 'technology'), name='unique_project_and_technology_pair'),
        ),
    ]
