# Generated by Django 3.1.5 on 2021-02-15 17:56

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Project = apps.get_model('portfolio', 'Project')
    TechnologyPerProject = apps.get_model('portfolio', 'TechnologyPerProject')
    for project in Project.objects.all():
        for technology in project.technologies.all():
            TechnologyPerProject.objects.create(
                project=project,
                technology=technology,
                how=''
            )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210214_1828'),
    ]

    operations = [
        migrations.RunPython(
            create_through_relations,
            reverse_code=migrations.RunPython.noop
        )
    ]
