# Generated by Django 3.1.5 on 2021-02-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', through='portfolio.TechnologyPerProject', to='portfolio.Technology'),
        ),
    ]
