# Generated by Django 3.1.5 on 2021-02-15 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyperproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies_per_project', to='portfolio.project'),
        ),
    ]
